import {normalize} from '../utils/deviceStyle';

export default {
  FONT_SIZE_SMALL: normalize(12),
  FONT_SIZE_NORMAL: normalize(14),
  FONT_SIZE_MEDIUM: normalize(16),
  FONT_SIZE_LARGE: normalize(18),
  FONT_SIZE_VERY_LARGE: normalize(22),
  FONT_SIZE_VERY_VERY_LARGE: normalize(25),
  // FONT_SIZE_VERY_VERY_LARGE:  normalize(35),
  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_NORMAL: 400,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 800,
  GREEN_BLUE: '#396974',
  BUTTON_GREEN_BACKGROUND: '#329D9C',
  BORDER_COLOR: '#BBBB',
  CONTENT_GREEN_BACKGROUND: '#E0ECDE',
  TEXT_BLUE_COLOR: '#205072',
  BACKGROUND_COLOR_GREEN: '#EEFAEC',
  BACKGROUND_COLOR_BLUE: '#CDE0C9',
  ICON_SIZE_MEDIUM: normalize(20),
};
