/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:366f8700-1160-412a-8082-71242f428b58",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Fq1QH51WX",
    "aws_user_pools_web_client_id": "2mib10kp7715nli3o7bcuc7qrq",
    "oauth": {}
};


export default awsmobile;
